const TASKIFY_THEME_COLOR = '#F38D8D';
const TASKIFY_WHITE_COLOR = '#FFFFFF';
const TASKIFY_DARK_PINK_COLOR = '#D2C0C0';
const API_PREFIX = 'https://taskify-api2.fly.dev';
// const API_PREFIX = 'http://localhost:8000';

export {
	TASKIFY_THEME_COLOR,
	TASKIFY_WHITE_COLOR,
	TASKIFY_DARK_PINK_COLOR,
	API_PREFIX,
};
